# Generated by Django 4.1 on 2022-08-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='vivo',
        ),
    ]
